### PR TITLE
BUG(Profile): deleting OF image gets me 404 page

### LINKED ISSUE #1581: BUG(Profile): deleting OF image gets me 404 page
## What is the current behavior?

I deleted my background image on My profile /links/ page. And now I see 404 page that my account is yet to be unlocked

## What is the expected behavior?

To not see cover background image I suppose, but see that my account is unlocked

Screenshot 2023-02-06 at 12 32 40

### PR DESCRIPTION
**Pull request by Cosmin-Parvulescu**
# Description

There is an exception thrown when no cover photo is set and the image worker expects it in order to generate the header OG profile image. This PR supposedly fixes this issue.

- Closes #1581 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

1. Remove cover image
2. See that 404 is not thrown anymore, but empty cover is presented

### CODE REVIEW

File: platform/images/src/jsonrpc/methods/getOgImage.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { svg2png, initialize } from 'svg2png-wasm'
 import { Context } from '../../context'
 
 export const getOgImageMethodInput = z.object({
-  bgUrl: z.string().url(),
```
Comment (maurerbot) [inline platform/images/src/jsonrpc/methods/getOgImage.ts:8]: url or string literal empty

**Review by maurerbot — APPROVED** [review]
